apiVersion: v1
kind: Template
metadata:
  name: znc

parameters:

- name: NAME
  description: The name of the app.
  value: znc

- name: PVC
  description: The name of a PersistentVolumeClaim which will be mounted as ZNC's data directory.
  value: znc

- name: IMAGE
  description: The ZNC Docker image to use.
  value: ironcladlou/znc:slim

- name: IMAGE_PULL_POLICY
  description: How to handle updates to the image.
  value: Always

objects:

- apiVersion: v1
  kind: Service
  metadata:
    name: ${NAME}
    labels:
      app: ${NAME}
  spec:
    type: ClusterIP
    sessionAffinity: ClientIP
    selector:
      app: ${NAME}
    ports:
    - name: znc
      port: 443
      protocol: TCP
      targetPort: 8080

- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    port:
      targetPort: znc
    tls:
      termination: passthrough
    to:
      kind: Service
      name: ${NAME}

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${NAME}
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${NAME}
    labels:
      app: ${NAME}
  spec:
    replicas: 1
    selector:
      app: ${NAME}
    strategy:
      type: Recreate
    triggers:
    - type: ConfigChange
    template:
      metadata:
        labels:
          app: ${NAME}
      spec:
        volumes:
        - name: data
          persistentVolumeClaim:
            claimName: ${PVC}
        containers:
        - name: znc
          image: ${IMAGE}
          imagePullPolicy: ${IMAGE_PULL_POLICY}
          livenessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTPS
            initialDelaySeconds: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTPS
            initialDelaySeconds: 3
            periodSeconds: 5
          volumeMounts:
          - name: data
            mountPath: /znc-data
            readOnly: false
